### ISSUE TITLE
Is it possible to add some texture to model?

### ISSUE THREAD

**Issue by KonradSzewczuk** [dbrant/ModelViewer3D#1]
@dbrant 
It would be cool, if will be possible to set texture on model e.g some picture, logo on a cup model or something. 
I mean something similiar to this: https://github.com/Rajawali/Rajawali/wiki/Materials

Is it possible to do it right now?

**Comment by sunjunlishi** [comment]
yes obj texture

**Comment by khawar408** [comment]
how to apply the texture on model
