### ISSUE TITLE
OOM Error

### ISSUE THREAD

**Issue by 8824PPZ** [dbrant/ModelViewer3D#13]
`Caused by: java.lang.OutOfMemoryError: Failed to allocate a 76144771 byte allocation with 25165824 free bytes and 36MB until OOM, max allowed footprint 255490976, growth limit 268435456` 
When I load 100MB STL file ,it throw this error. How to solve this question?

**Comment by dbrant** [comment]
A 100MB model file is too large to be loaded into a simple app like this. It's not a problem with the app, but a limitation of the Java VM size.
