### ISSUE TITLE
How draw the PLY model with rgb alpha property?

### ISSUE THREAD

**Issue by ApplicateIT-Thang** [dbrant/ModelViewer3D#16]
Hi Brant, 
As I saw in the code to read the PLY object, you only read the x,y,z properties.

> property float x
property float y
property float z

The model will be displayed in the gray color mode.
How to draw the PLY model with rgb colors when the file headers contains rgb elements?

> property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
property uchar alpha

Thank you very much.
Regards,
KieuThang

**Comment by dbrant** [comment]
You would probably need to create a new shader that accounts for different colors for each point.
Can you provide an example PLY file that contains color data?

**Comment by ApplicateIT-Thang** [comment]
Hi, 
Yes, please try this example PLY file with color data.
[simple.ply.zip](https://github.com/dbrant/ModelViewer3D/files/6255928/simple.ply.zip).
Thank you.

**Comment by dbrant** [comment]
Done! Can you try the latest code?  I have also released an update to the Play Store, but that may still take a few hours.

It might also be helpful to get a few additional PLY models with color data in them.  Would you be able to provide a couple more for testing purposes?

**Comment by ApplicateIT-Thang** [comment]
Hi Brant,
It works perfectly.
![Screenshot_20210408-085433_3D Model Viewer](https://user-images.githubusercontent.com/73826280/113956521-c8915600-9847-11eb-864f-6bb6a4c3ff1c.jpg)
As you see, the model is displayed with color now :).

Please check those samples for the PLY models with RGB elements.
[girl.ply.zip](https://github.com/dbrant/ModelViewer3D/files/6275471/girl.ply.zip)
[leg.ply.zip](https://github.com/dbrant/ModelViewer3D/files/6275474/leg.ply.zip)
[girl3.ply.zip](https://github.com/dbrant/ModelViewer3D/files/6275479/girl3.ply.zip)
[leg2.ply.zip](https://github.com/dbrant/ModelViewer3D/files/6275480/leg2.ply.zip)

Thank you so much for your awesome support.
Have a nice day.
Regards,
KieuThang.

**Comment by dbrant** [comment]
Thanks!
