### ISSUE TITLE
Fix intent-filter to open files from the file browser / downloads view

### ISSUE THREAD

**Issue by forivall** [dbrant/ModelViewer3D#18]
Like default file associations.

File managers used:
* Files by Google 1.0.406984716
* simplemobiletools [File Manager](https://f-droid.org/en/packages/com.simplemobiletools.filemanager.pro/) 6.11.2

Pixel 3, Android 12, security update October 5, 2021

**Comment by dbrant** [comment]
The app already has an intent-filter for `.stl` files, which should work from a browser or file manager.  Is there a case for which it's not working? Or do you have another file extension in mind?

**Comment by forivall** [comment]
Yeah, it's .stl that's not working. There's a few other apps for which the intent is working, the best one being [CAD Assistant](https://dev.opencascade.org/project/cad-assistant), but unfortunately, it's freeware and not open source, so i can't tell the difference (tho you probably can look at the manifest - i haven't dabbled with android dev in a few years, so i dont remember.)

_Updated the origin comment to add system info._

**Comment by forivall** [comment]
Yeah, using `apktool` and looking at their `AndroidManifest.xml`, i'm guessing 
```xml
                <action android:name="android.intent.action.OPEN_DOCUMENT"/>
                <category android:name="android.intent.category.OPENABLE"/>
```
may solve the problem.

**Comment by forivall** [comment]
Wait, it's working now. Maybe there's like a cache of the intents that was stale? Idk. Anyways, probably good to know for future reference. Sorry for the unnecessary notifications and/or worry 😝

**Comment by forivall** [comment]
Actually, it probably wouldn't hurt to add that extra metadata: basically, things are inconsistent

Simple mobile tools file manager still misses the entry:
![Screenshot_20211220-204047.png](https://user-images.githubusercontent.com/760204/146872380-6c2543f4-5325-4eeb-b30e-ed96526de4a3.png)

But navigating to "internal storage" in files by Google works...
![Screenshot_20211220-204116.png](https://user-images.githubusercontent.com/760204/146872514-bed93167-a52b-43f2-bc41-c1cfd0f66a29.png)

(But not when looking at "downloads" in files by Google)
![Screenshot_20211220-204101.png](https://user-images.githubusercontent.com/760204/146872531-ed9b01cb-8245-4b52-bb03-f3756ca83911.png)

**Comment by dbrant** [comment]
Thanks for the update -- I'll look into adding the `OPEN_DOCUMENT` action. (Admittedly I've been behind on testing this on more recent versions of Android.)
