### ISSUE TITLE
How can I speed up the viewer?

### ISSUE THREAD

**Issue by TejNote** [dbrant/ModelViewer3D#20]
hello. Thanks to your help last time, I am currently developing a function using the library.  
  
The device we are using is the Galaxy Tab S7, but there is a phenomenon where the speed is very slow when using the viewer  because it has only 4 gigabytes of memory.  
  
Is there any way to improve the speed?  
Or can you tell me how I can clear the matrix lines in the viewer?  
  
Thank you for always.

**Comment by dbrant** [comment]
This needs much more information:

* Does it behave slowly when loading any model (even a small model), or only complex models?
* How do you know that the slowness is because the device has 4GB or memory?
* What do you mean by "clear the matrix lines"?

**Comment by TejNote** [comment]
1. Does it behave slowly when loading any model (even a small model), or only complex models?  
   * It is this file. [full_part_refined.ply.zip](https://github.com/dbrant/ModelViewer3D/files/11090560/full_part_refined.ply.zip)  
  
2. How do you know that the slowness is because the device has 4GB or memory?  
   * I am currently using the Galaxy S23 Ultra.  
      When tested on the cell phone, it worked smoothly without slowing down.  
      Testing on a Galaxy S7 tab, it started to slow down.  
  
3. What do you mean by "clear the matrix lines"?  
    * I expected that minimizing drawing to OpenGL would speed things up.  
       So I asked if it would be faster if I deleted the grid lines on the screen.

**Comment by TejNote** [comment]
Thank you for answer.
As dbrant said, we decided that 500000 vertices was too many, and reduced the amount of data by not adding vertices at regular intervals.

Since the amount of data is reduced, the quality is reduced, but the speed is greatly improved.

Thank you for always responding quickly.
thanks it helped a lot.
