### ISSUE TITLE
read large who have face ply is not same with Meshalab or CloudCompare showing

### ISSUE THREAD

**Issue by nocamles** [dbrant/ModelViewer3D#22]
i don't know what going on,It seems like the data for triangle vectors is stuck together, showing incorrect triangles. I tried to filter out the parsed triangles by their area size, but it was unsuccessful.  still stuck together. I hope you can provide some ideas or suggestions for me to solve this issue.
[ply_show.zip](https://github.com/dbrant/ModelViewer3D/files/11260979/ply_show.zip)

**Comment by dbrant** [comment]
That's very weird -- it looks correct on my devices when I try it:

![image](https://user-images.githubusercontent.com/1682214/232780354-bfc301bc-3117-46eb-8f49-86df8ba589ce.png)

It's possible that there's some kind of device-specific issue (or manufacturer-specific issue) with your device's GLES version, but this would be beyond my ability to diagnose. :(

**Comment by nocamles** [comment]
The problem was indeed caused by the version of the device. When I tried running it on my colleague's Oppo Android phone, it worked fine. This issue cannot be resolved, lol.
