### ISSUE TITLE
404 Could not find com.google.vr:sdk-base:1.130.0.

### ISSUE THREAD

**Issue by jmhe1** [dbrant/ModelViewer3D#23]
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.google.vr:sdk-base:1.130.0.
Searched in the following locations:
  - https://repo1.maven.org/maven2/com/google/vr/sdk-base/1.130.0/sdk-base-1.130.0.pom
  - https://dl.google.com/dl/android/maven2/com/google/vr/sdk-base/1.130.0/sdk-base-1.130.0.pom
  - file:/C:/Users/DELL/.m2/repository/com/google/vr/sdk-base/1.130.0/sdk-base-1.130.0.pom
  - https://repo.maven.apache.org/maven2/com/google/vr/sdk-base/1.130.0/sdk-base-1.130.0.pom

**Comment by dbrant** [comment]
Not sure I understand what the question is.
This project uses the VR SDK version 1.190.0, not 1.130.0.  If your project uses 1.130.0, I would suggest updating.
