### ISSUE TITLE
how to add Material and Texture in obj file.

### ISSUE THREAD

**Issue by nocamles** [dbrant/ModelViewer3D#25]
I noticed there are TODOs in your objModel related to vt parsing. Is this related to textures and materials in obj files? Could you share the implementation approach? Thank you verymuch

**Comment by dbrant** [comment]
> I noticed there are TODOs in your objModel related to vt parsing. Is this related to textures and materials in obj files? Could you share the implementation approach? Thank you verymuch

Yes, those TODOs are for parsing texture coordinates, if we ever support loading textures. There is no implementation approach, since we don't support loading textures.
