### ISSUE TITLE
关于使用Matrix.setLookAtM() Z轴缩放后，手指移动距离与模型移动距离1:1的问题

### ISSUE THREAD

**Issue by zzyyppqq** [dbrant/ModelViewer3D#27]
translateScaleFactor为什么要这样赋值[val translateScaleFactor = MODEL_BOUND_SIZE / 200f]，移动模型时发现移动距离和手指滑动的距离不是1:1的关系，模型缩放越小，滑动的距离越小；1.如何计算平移因子和实际的像素1:1移动？
2.通过Matrix.setLookAtM() z轴缩放模型与使用Matrix.scaleM() 最终计算平移因子有什么区别？
3.MODEL_BOUND_SIZE对平移因子的影响？

 

https://github.com/dbrant/ModelViewer3D/blob/master/app/src/main/java/com/dmitrybrant/modelviewer/ModelRenderer.kt

```kotlin
fun translate(dx: Float, dy: Float, dz: Float) {
        val translateScaleFactor = MODEL_BOUND_SIZE / 200f
        translateX += dx * translateScaleFactor
        translateY += dy * translateScaleFactor
        if (dz != 0f) {
            translateZ /= dz
        }
        updateViewMatrix()
    }
```

是否要提取矩阵变换的缩放因子，来计算translateScaleFactor，使模型移动距离和手指滑动的距离比是1:1的关系？

```kotlin
private val tempMatrix = FloatArray(16)
fun translate(dx: Float, dy: Float, dz: Float) {
        Matrix.multiplyMM(tempMatrix, 0, projectionMatrix, 0, viewMatrix, 0);
        // 提取缩放因子
        val scaleX = tempMatrix[0]
        val scaleY = tempMatrix[5]
        val scaleZ = tempMatrix[10]
}
```

**Comment by dbrant** [comment]
Sorry, I'm able to reply in English only.

**Comment by zzyyppqq** [comment]
Why is translateScaleFactor assigned like this [val translateScaleFactor = MODEL_BOUND_SIZE / 200f]? When moving the model, it is found that the moving distance and the finger sliding distance are not in a 1:1 relationship. The smaller the model is scaled, the smaller the sliding distance is. 1. How to calculate the translation factor and the actual pixel 1:1 movement? 
2. What is the difference between scaling the model on the z-axis through Matrix.setLookAtM() and using Matrix.scaleM() to finally calculate the translation factor? 
3. The impact of MODEL_BOUND_SIZE on the translation factor?

https://github.com/dbrant/ModelViewer3D/blob/master/app/src/main/java/com/dmitrybrant/modelviewer/ModelRenderer.kt
```kotlin
fun translate(dx: Float, dy: Float, dz: Float) {
        val translateScaleFactor = MODEL_BOUND_SIZE / 200f
        translateX += dx * translateScaleFactor
        translateY += dy * translateScaleFactor
        if (dz != 0f) {
            translateZ /= dz
        }
        updateViewMatrix()
    }

```

Do we need to extract the scaling factor of the matrix transformation to calculate translateScaleFactor so that the model movement distance and finger sliding distance have a 1:1 relationship?

```kotlin
private val tempMatrix = FloatArray(16)
fun translate(dx: Float, dy: Float, dz: Float) {
        Matrix.multiplyMM(tempMatrix, 0, projectionMatrix, 0, viewMatrix, 0);
        // 提取缩放因子
        val scaleX = tempMatrix[0]
        val scaleY = tempMatrix[5]
        val scaleZ = tempMatrix[10]
}
```
