### ISSUE TITLE
About the problem of using Matrix.setLookAtM() to scale the Z axis so that the finger movement distance is 1:1 with the model movement distance

### ISSUE THREAD

**Issue by zzyyppqq** [dbrant/ModelViewer3D#28]
Why is translateScaleFactor assigned like this [val translateScaleFactor = MODEL_BOUND_SIZE / 200f]? When moving the model, it is found that the moving distance and the finger sliding distance are not in a 1:1 relationship. The smaller the model is scaled, the smaller the sliding distance is. 1. How to calculate the translation factor and the actual pixel 1:1 movement? 
2. What is the difference between scaling the model on the z-axis through Matrix.setLookAtM() and using Matrix.scaleM() to finally calculate the translation factor? 
3. The impact of MODEL_BOUND_SIZE on the translation factor?

https://github.com/dbrant/ModelViewer3D/blob/master/app/src/main/java/com/dmitrybrant/modelviewer/ModelRenderer.kt
```kotlin
fun translate(dx: Float, dy: Float, dz: Float) {
        val translateScaleFactor = MODEL_BOUND_SIZE / 200f
        translateX += dx * translateScaleFactor
        translateY += dy * translateScaleFactor
        if (dz != 0f) {
            translateZ /= dz
        }
        updateViewMatrix()
    }

```

Do we need to extract the scaling factor of the matrix transformation to calculate translateScaleFactor so that the model movement distance and finger sliding distance have a 1:1 relationship?

```kotlin
private val tempMatrix = FloatArray(16)
fun translate(dx: Float, dy: Float, dz: Float) {
        Matrix.multiplyMM(tempMatrix, 0, projectionMatrix, 0, viewMatrix, 0);
        // 提取缩放因子
        val scaleX = tempMatrix[0]
        val scaleY = tempMatrix[5]
        val scaleZ = tempMatrix[10]
}
```

**Comment by dbrant** [comment]
> Why is translateScaleFactor assigned like this [val translateScaleFactor = MODEL_BOUND_SIZE / 200f]? When moving the model, it is found that the moving distance and the finger sliding distance are not in a 1:1 relationship.

I did it this way because it's good enough. For my purposes it didn't need to be a 1:1 relationship.
If you want to make it a 1:1 relationship, you may use whatever method you like. I'm not sure I can comment on what would be the best solution here -- Feel free to experiment.

**Comment by zzyyppqq** [comment]
Thank you so much
