### ISSUE TITLE
Some binary files contain "solid $filename" in the header of the files

### ISSUE THREAD

**Issue by tobybonhof** [dbrant/ModelViewer3D#3]
Some files on thingiverse actually contains "solid $filename" in the header of the file which makes the renderer think it's a text-based files which is not the case, and makes it so that the file can't be parsed.

https://www.thingiverse.com/thing:2676324/#files
These files can't get viewed because of this error.

Snippet of the binary data:
`
solid measuring_mini_cube_22aa                                                  †˚ÄøÕ¯å *˝$gfãBHåBröBgfãBPåBúBgfãBPåBffBÄøÕ¯å *˝$gfãB/yçBPWÕAgfãBh\çB¶ÀAgfãBh\çB=f‘AÄøÕ¯å *˝$gfãBmçB†èDAgfãB"EìB†èDAgfãB"EìBæ‚?AÄøÕ¯å *˝$gfãBŸ≤îBJRAgfãBmçBJRAgfãBh\çB!MXAÄøÕ¯å *˝$gfãBh\çB!MXAgfãBmçBJRAgfãBh\çBæ‚?AÄøÕ¯å *˝$gfãBmçBJRAgfãBmçB†èDAgfãBh\çBæ‚?AÄøÕ¯å *˝$gfãBh\çBæ‚?AgfãBmçB†èDAgfãB"EìBæ‚?AÄøÕ¯å *˝$gfãBh\çBæ‚?AgfãB"EìBæ‚?AgfãBh\çBAÄøÕ¯å *˝$gfãBh\çBAgfãB"EìBæ‚?
`

However the file is acutally legit, because it can be openend in some other STL viewer on the play store, also Ultimaker Cura for desktop has no problems viewing the model

**Comment by tobybonhof** [comment]
I will try to figure it out, and make a pr when i have, but just wanted to let you know

**Comment by tobybonhof** [comment]
Turns out when returning false for isTextFormat, these files get rendered properly, i will try to make a more, definitive way of detecting wether the file is binary or textual

**Comment by tobybonhof** [comment]
By Increasing the testbytes by 5 times. and checking the test string for "solid" && "vertex" this issue got fixed for me, what do you think?

`
        byte[] testBytes = new byte[HEADER_SIZE * 5];
        stream.read(testBytes, 0, testBytes.length);
        String string = new String(testBytes);
        return string.contains("solid") && string.contains("vertex");
`

**Comment by dbrant** [comment]
Thanks for that link. It looks like some STL files don't exactly follow the expected specification (i.e. binary files starting with `solid`).

Yes, your logic should work pretty well. I made some commits that integrate this logic, as well as some more optimizations, which should fix the issue (and make the app compatible with a wider range of STL files). Feel free to reopen the issue if you find any other problematic files.
