### ISSUE TITLE
Is it possible to get part name of 3D Object?

### ISSUE THREAD

**Issue by HariharanEswaran** [dbrant/ModelViewer3D#7]
Ques 1:
I have to added Human 3D object file using your excellent Renderer code,and the 3D object have multiple body parts(Head,Leg,etc..).So,Using OnTouch event can i have selected 3D model part name??

Ques 2:
Is it possible to load more than one Obj file at same time in a SurfaceView??

Thanks in Advance

**Comment by dbrant** [comment]
> Using OnTouch event can i have selected 3D model part name?

You would have to implement a "picking" algorithm to transform your touch coordinates into the world space of the model and detect which portion of the model is picked.

> Is it possible to load more than one Obj file at same time in a SurfaceView?

Sure, right now the model is stored as a global field in `ModelViewerApplication.java`. You can change this to be a `List` of models, and then render all of them in `ModelRenderer.onDrawFrame()`.

**Comment by HariharanEswaran** [comment]
I have to try with your tips for load more than one object file at same time in a surfaceview.But its not working for me.
	Please help me!,If you have sample source pls share the link.
Please find below my Source
	
	Step 1: Application class
	   @Nullable
    private List<Model> currentModel;

    public static ModelViewerApplication getInstance() {
        return INSTANCE;
    }

    @Nullable
    public List<Model> getCurrentModel() {
        return currentModel;
    }

    public void setCurrentModel(@Nullable List<Model> model) {
        currentModel = model;
    }
	
	Step 2: MainActivity
        List<Model> modelList = new ArrayList<>();
        try {
            InputStream stream = getApplicationContext().getAssets().open(SAMPLE_MODELS[0]);
            Model model = new ObjModel(stream);
            stream.close();
            modelList.add(model);

            InputStream stream1 = getApplicationContext().getAssets().open(SAMPLE_MODELS[1]);
            Model model1 = new ObjModel(stream1);
            stream1.close();
            modelList.add(model1);

            setCurrentModel(modelList);
        } catch (IOException e) {
            e.printStackTrace();
        }

Step 3: Rederer class

  @Override
    public void onDrawFrame(GL10 unused) {
        GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT | GLES20.GL_DEPTH_BUFFER_BIT);

        floor.draw(viewMatrix, projectionMatrix, light);
        if (model != null) {
            for (int i = 0; i < model.size(); i++) {
                model.get(i).draw(viewMatrix, projectionMatrix, light);
            }
        }
    }

**Comment by braver-tool** [comment]
> I have to try with your tips for load more than one object file at same time in a surfaceview.But its not working for me.
> Please help me!,If you have sample source pls share the link.
> Please find below my Source
> 
> ```
> Step 1: Application class
>    @Nullable
> private List<Model> currentModel;
> 
> public static ModelViewerApplication getInstance() {
>     return INSTANCE;
> }
> 
> @Nullable
> public List<Model> getCurrentModel() {
>     return currentModel;
> }
> 
> public void setCurrentModel(@Nullable List<Model> model) {
>     currentModel = model;
> }
> 
> Step 2: MainActivity
>     List<Model> modelList = new ArrayList<>();
>     try {
>         InputStream stream = getApplicationContext().getAssets().open(SAMPLE_MODELS[0]);
>         Model model = new ObjModel(stream);
>         stream.close();
>         modelList.add(model);
> 
>         InputStream stream1 = getApplicationContext().getAssets().open(SAMPLE_MODELS[1]);
>         Model model1 = new ObjModel(stream1);
>         stream1.close();
>         modelList.add(model1);
> 
>         setCurrentModel(modelList);
>     } catch (IOException e) {
>         e.printStackTrace();
>     }
> ```
> 
> Step 3: Rederer class
> 
> @override
> public void onDrawFrame(GL10 unused) {
> GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT | GLES20.GL_DEPTH_BUFFER_BIT);
> 
> ```
>     floor.draw(viewMatrix, projectionMatrix, light);
>     if (model != null) {
>         for (int i = 0; i < model.size(); i++) {
>             model.get(i).draw(viewMatrix, projectionMatrix, light);
>         }
>     }
> }
> ```

I still not complete this, and also I tried with your updated source for my above question, but it's not working for me, So Could you share code to load more than one object file in the same surface view https://github.com/dbrant/ModelViewer3D/issues/7#issuecomment-480032248 ?
