### ISSUE TITLE
Is it possible to get stereoscopic mode without involving Cardboard?

### ISSUE THREAD

**Issue by MarcoCozza** [dbrant/ModelViewer3D#8]
I'm trying to use this app on a device which displays wrong apps based on cardboard but works fine with stereoscopic media. So I was wandering if there's a way to get stereoscopic without involving Cardboard

**Comment by dbrant** [comment]
This app uses the Google VR SDK, which requires either Cardboard or Daydream. There may be other SDKs that display stereoscopic media, but I'm not familiar with them...
