### ISSUE TITLE
Can I user my material file for the .obj 3d model

### ISSUE THREAD

**Issue by SagarKhurana** [dbrant/ModelViewer3D#9]
Hi @dbrant, thanks for this library. 
I could see that you have created custom params for the lighting attributes like ambient, specular and diffuse. 
but is there any possibility to use our own custom .mtl for the .obj files. 

I want to load the .obj files to the 3d model viewer but currently, it is showing as per the lighting we set in the Light class. 
looking forward to your response.
Thanks in advance.

**Comment by gitcitu1** [comment]
support now?

**Comment by gitcitu1** [comment]
Has it been resolved? I didn't see a solution.
